type: group
fields:
  securedpageenabled:
    type: toggle
    label: 
      en: Page Protection
      de: Seitensichtbarkeit
    text: 
      en: Enable the page password protection?
      de: Die Seite mit Passwort schützen?

  securedpageroles:
    label: 
      en: Roles
      de: Rollen
    type: multiselect
    options: query
    when:
      securedpageenabled: true
    query:
      fetch: kirby.roles
      text: "{{ item.title }}"
      value: "{{ item.id }}"
